version: '3.8'
services:

  app:
    build: .
    command: sh -c "python manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
    - .:/app
    ports:
      - "8000:8000"

  worker:
    build: .
    command: sh -c "/app/wait-for redis:6379 && /app/wait-for app:8000 && celery -A config.celery worker -l info"
    env_file:
      - .env
    volumes:
      - .:/app

  heartbeat:
    build: .
    command: sh -c "/app/wait-for redis:6379 && /app/wait-for app:8000 && celery -A config.celery beat -l info"
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=${DJANGO_DB_NAME}"
      - "POSTGRES_USER=${DJANGO_DB_USER}"
      - "POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}"

  redis:
    image: bitnami/redis:latest
    env_file:
      - .env

