# Generated by Django 3.2.4 on 2021-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.IntegerField()),
                ('status', models.CharField(max_length=256)),
                ('order_key', models.CharField(max_length=256)),
                ('total', models.FloatField(default=0.0)),
            ],
        ),
    ]
