# Generated by Django 3.2.4 on 2021-06-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='link',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
