# Generated by Django 3.2.4 on 2021-06-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('sku', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(default='draft', max_length=256)),
                ('regular_price', models.FloatField(default=0.0)),
                ('sale_price', models.FloatField(default=0.0)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
