# Generated by Django 3.2.4 on 2021-06-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo_products', '0002_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='draft', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
