# Generated by Django 3.2.4 on 2021-06-24 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0001_initial'),
        ('woo_products', '0002_auto_20210623_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_sku', models.CharField(max_length=256)),
                ('price', models.FloatField(default=0.0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contact.contact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woo_products.product')),
            ],
        ),
    ]
