# Generated by Django 3.2.4 on 2021-06-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo_products', '0003_productcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
