# Generated by Django 3.2.4 on 2021-06-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woo_products', '0004_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontact',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='woo_products.product'),
        ),
    ]
