# Generated by Django 3.2.4 on 2021-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo_media', '0002_media_link'),
        ('woo_products', '0005_alter_productcontact_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='products', to='woo_media.Media'),
        ),
    ]
