# Generated by Django 3.2.4 on 2021-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo_products', '0006_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
