# Generated by Django 3.2.4 on 2021-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo_products', '0007_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
