# Generated by Django 3.2.4 on 2021-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo_products', '0008_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
